// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA85CPAxcF9N8e_8SPSkegVNZFBzbVGuw',
    appId: '1:1050572950478:web:daec0a594c88db551cf99f',
    messagingSenderId: '1050572950478',
    projectId: 'amitylinkmobile-f41ff',
    authDomain: 'amitylinkmobile-f41ff.firebaseapp.com',
    storageBucket: 'amitylinkmobile-f41ff.appspot.com',
    measurementId: 'G-WJJGB3EEF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl16RMkDc4NkLvjcITACUgqaDpCyQUJSE',
    appId: '1:1050572950478:android:a2ace60f1fbd067b1cf99f',
    messagingSenderId: '1050572950478',
    projectId: 'amitylinkmobile-f41ff',
    storageBucket: 'amitylinkmobile-f41ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3Xf7UjYOFlbDd0o8SLD6HIcxiCF24XRI',
    appId: '1:1050572950478:ios:50daa8e2447974081cf99f',
    messagingSenderId: '1050572950478',
    projectId: 'amitylinkmobile-f41ff',
    storageBucket: 'amitylinkmobile-f41ff.appspot.com',
    iosBundleId: 'com.example.amityLinkMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3Xf7UjYOFlbDd0o8SLD6HIcxiCF24XRI',
    appId: '1:1050572950478:ios:89ac963d14d5d2cc1cf99f',
    messagingSenderId: '1050572950478',
    projectId: 'amitylinkmobile-f41ff',
    storageBucket: 'amitylinkmobile-f41ff.appspot.com',
    iosBundleId: 'com.example.amityLinkMobile.RunnerTests',
  );
}
